### ISSUE TITLE
Node style callbacks

### ISSUE THREAD

**Issue by bradvogel** [Droplr/screenbot-js#1]
It would be nice to have the callbacks be Node-style and more consistent with JS ecosystem, with the error object (which is type `Error`) passed first (or null for success), and then the result as the second param.

So on success:

```
sb.shot(function(err, result){
  // err: null
  // result: {url: 'https://droplr.com/i...}
});
```

and on failure:

```
sb.shot(function(err, result){
  // err: new Error('Screenbot not installed...') - and it has a .code property with the enum error code
  // result: null
});
```

**Comment by nrbernard** [comment]
@bradvogel Totally agree. Callbacks now expect `err` and `result` parameters. `result` is an object that either has a `url` property that points to the uploaded drop, or a `connected` property in the case of the `ping` command.
