### ISSUE TITLE
A command to tell if the user has Screenbot running

### ISSUE THREAD

**Issue by bradvogel** [Droplr/screenbot-js#2]
It'd be nice to have a command (perhaps `ping` or `isActivated`?) to tell if the user is running Screenbot, prior to actually triggering a command. The use case for this is to show the app upsell UX upfront.

**Comment by nrbernard** [comment]
@bradvogel Thanks for that request! I've added a `ping` command in release v0.1.1 that returns a response with a `connected` property that's either `true` or `false`.
